backend:
  service:
    name: deeptsf-backend
  image:
    repository: harbor.aiodp.ai/iccs/deeptsf-backend
  replicas: 1
  memory_limit: 4Gi

dagster:
  service:
    name: deeptsf-dagster
  image:
    repository: harbor.aiodp.ai/iccs/deeptsf-dagster
  replicas: 1
  memory_limit: 4Gi

worker:
  service:
    name: deeptsf-worker
  image:
    repository: harbor.aiodp.ai/iccs/deeptsf-worker
  replicas: 1
  memory_limit: 4Gi

pgdb:
  service:
    name: deeptsf-pgdb
  image:
    repository: harbor.aiodp.ai/iccs/deeptsf-pgdb
  replicas: 1
  memory_limit: 1Gi

redis:
  service:
    name: deeptsf-redis
  image:
    repository: harbor.aiodp.ai/iccs/deeptsf-redis
  replicas: 1
  memory_limit: 1Gi

minio:
  ssl: false

env:
  host: ""
  marketplace: ""
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  MINIO_CLIENT_URL: ""
  MINIO_SSL: ""
  MLFLOW_TRACKING_URI: ""
  MLFLOW_S3_ENDPOINT_URL: ""
  MINIO_ACCESS_KEY: ""
  MINIO_SECRET_KEY: ""
  USE_AUTH: ""
  KEYCLOAK_ID: ""
  KEYCLOAK_SECRET: ""
  TOKEN_ISSUER_URL: ""
  PYTHONUNBUFFERED: ""
  CELERYD_HIJACK_ROOT_LOGGER: ""
  CELERY_BROKER_URL: ""
  CELERY_RESULT_BACKEND: ""
  POSTGRES_USER: ""
  POSTGRES_DATABASE: ""
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST: ""
  VERSION: ""
  DAGSTER_HOME: "/app/dagster_deeptsf"

ingress:
  enabled: true
  tlsSecretName: deeptsf-tls
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

storage:
  size: 20Gi