app:
  host: deeptsf-backend.dev.deployai.eu
  service:
    name: deeptsf-backend
  image:
    repository: harbor.deployai.eu/iccs/deeptsf-backend
    tag: latest
  env:
    AWS_ACCESS_KEY_ID: ""
    AWS_SECRET_ACCESS_KEY: ""
    MINIO_CLIENT_URL: ""
    MINIO_SSL: ""
  replicas: 1
  memory_limit: 4Gi

minio:
  ssl: false

ingress:
  enabled: true
  tlsSecretName: deeptsf-backend-tls
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"