app:
  host: deeptsf-backend.dev.deployai.eu
  service:
    name: deeptsf-backend
  image:
    repository: harbor.deployai.eu/iccs/deeptsf-backend
    tag: latest
  env:
    APP_BACKEND_URL: "deeptsf-backend.dev.deployai.eu"
  replicas: 1
  memory_limit: 4Gi

ingress:
  enabled: true
  tlsSecretName: deeptsf-backend-tls
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"