backend:
  service:
    name: deeptsf-backend
  image:
    repository: harbor.aiodp.ai/iccs/deeptsf-backend
    tag: latest
  replicas: 1
  memory_limit: 4Gi

dagster:
  service:
    name: deeptsf-dagster
  image:
    repository: harbor.aiodp.ai/iccs/deeptsf-dagster
    tag: latest
  replicas: 1
  memory_limit: 4Gi

minio:
  ssl: false

env:
  host: ""
  marketplace: ""
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  MINIO_CLIENT_URL: ""
  MINIO_SSL: ""
  MLFLOW_TRACKING_URI: ""
  MLFLOW_S3_ENDPOINT_URL: ""
  MINIO_ACCESS_KEY: ""
  MINIO_SECRET_KEY: ""
  USE_AUTH: ""
  KEYCLOAK_ID: ""
  KEYCLOAK_SECRET: ""
  TOKEN_ISSUER_URL: ""

ingress:
  enabled: true
  tlsSecretName: deeptsf-tls
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"