version: '3.3'
services:
  backend:
    container_name: DeepTSF-backend
    hostname: DeepTSF-backend
    build:
      context: .
      # dockerfile: ./Dockerfile_keycloak
    restart: always
    expose:
      - 8081
    ports:
      - "8081:8081"
    stdin_open: true
    # env_file:
    #   - .env
    networks:
       - inergy_network

networks:
  inergy_network:
    external: true