apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-{{ .Values.app.service.name }}"
  labels:
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.service.name }}
      release: {{ .Release.Name }} 
  template:
    metadata:
      labels:
        app: {{ .Values.app.service.name }}
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets: 
      - name: {{ .Release.Name }}-image-pull-secret
      containers:
      - name: deeptsf-backend
        image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
        imagePullPolicy: Always
        resources:
          limits:
            memory: {{ .Values.app.memory_limit | quote }}
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-{{ .Values.app.service.name }}-cm
        env:
        - name: AWS_ACCESS_KEY_ID
          value: {{ required "AWS_ACCESS_KEY_ID environment variable is required" .Values.app.env.AWS_ACCESS_KEY_ID | quote }}
        - name: AWS_SECRET_ACCESS_KEY
          value: {{ required "AWS_SECRET_ACCESS_KEY environment variable is required" .Values.app.env.AWS_SECRET_ACCESS_KEY | quote }}
        - name: MINIO_CLIENT_URL
          value: {{ required "MINIO_CLIENT_URL environment variable is required" .Values.app.env.MINIO_CLIENT_URL | quote }}
        - name: MINIO_SSL
          value: {{ required "MINIO_SSL environment variable is required" .Values.app.env.MINIO_SSL | quote }}
        - name: MLFLOW_TRACKING_URI
          value: {{ required "MLFLOW_TRACKING_URI environment variable is required" .Values.app.env.MLFLOW_TRACKING_URI | quote }}
        - name: MLFLOW_S3_ENDPOINT_URL
          value: {{ required "MLFLOW_S3_ENDPOINT_URL environment variable is required" .Values.app.env.MLFLOW_S3_ENDPOINT_URL | quote }}
        - name: MINIO_ACCESS_KEY
          value: {{ required "MINIO_ACCESS_KEY environment variable is required" .Values.app.env.MINIO_ACCESS_KEY | quote }}
        - name: MINIO_SECRET_KEY
          value: {{ required "MINIO_SECRET_KEY environment variable is required" .Values.app.env.MINIO_SECRET_KEY | quote }}
        - name: USE_KEYCLOAK
          value: {{ required "USE_KEYCLOAK environment variable is required" .Values.app.env.USE_KEYCLOAK | quote }}
        ports:
        - containerPort: 80