apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-{{ .Values.app.service.name }}"
  labels:
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.service.name }}
      release: {{ .Release.Name }} 
  template:
    metadata:
      labels:
        app: {{ .Values.app.service.name }}
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets: 
      - name: {{ .Release.Name }}-image-pull-secret
      containers:
      - name: deeptsf-backend
        image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
        imagePullPolicy: Always
        resources:
          limits:
            memory: {{ .Values.app.memory_limit | quote }}
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-{{ .Values.app.service.name }}-cm
        env:
        - name: AWS_ACCESS_KEY_ID
          value: {{ .Values.app.env.AWS_ACCESS_KEY_ID | default (required "AWS_ACCESS_KEY_ID environment variable is required" .Env.AWS_ACCESS_KEY_ID) | quote }}
        - name: AWS_SECRET_ACCESS_KEY
          value: {{ .Values.app.env.AWS_SECRET_ACCESS_KEY | default (required "AWS_SECRET_ACCESS_KEY environment variable is required" .Env.AWS_SECRET_ACCESS_KEY) | quote }}
        ports:
        - containerPort: 80