apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-deeptsf-dagster"
  labels:
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8006
  selector:
    app: {{ .Values.dagster.service.name }}
    release: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.dagster.service.name }}
  labels:
    app: {{ .Values.dagster.service.name }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.dagster.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.dagster.service.name }}
      release: {{ .Release.Name }} 
  template:
    metadata:
      labels:
        app: {{ .Values.dagster.service.name }}
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets: 
      - name: {{ .Release.Name }}-image-pull-secret
      containers:
      - name: deeptsf-dagster
        image: "{{ .Values.dagster.image.repository }}:{{ .Values.dagster.image.tag }}"
        imagePullPolicy: Always
        resources:
          limits:
            memory: {{ .Values.dagster.memory_limit | quote }}
        # envFrom:
        # - configMapRef:
        #     name: {{ .Release.Name }}-{{ .Values.dagster.service.name }}-cm
        env:
        - name: host
          value: {{ required "host environment variable is required" .Values.env.host | quote }}
        - name: marketplace
          value: {{ required "marketplace environment variable is required" .Values.env.marketplace | quote }}
        - name: AWS_ACCESS_KEY_ID
          value: {{ required "AWS_ACCESS_KEY_ID environment variable is required" .Values.env.AWS_ACCESS_KEY_ID | quote }}
        - name: AWS_SECRET_ACCESS_KEY
          value: {{ required "AWS_SECRET_ACCESS_KEY environment variable is required" .Values.env.AWS_SECRET_ACCESS_KEY | quote }}
        - name: MINIO_CLIENT_URL
          value: {{ required "MINIO_CLIENT_URL environment variable is required" .Values.env.MINIO_CLIENT_URL | quote }}
        - name: MINIO_SSL
          value: {{ required "MINIO_SSL environment variable is required" .Values.env.MINIO_SSL | quote }}
        - name: MLFLOW_TRACKING_URI
          value: {{ required "MLFLOW_TRACKING_URI environment variable is required" .Values.env.MLFLOW_TRACKING_URI | quote }}
        - name: MLFLOW_S3_ENDPOINT_URL
          value: {{ required "MLFLOW_S3_ENDPOINT_URL environment variable is required" .Values.env.MLFLOW_S3_ENDPOINT_URL | quote }}
        - name: MINIO_ACCESS_KEY
          value: {{ required "MINIO_ACCESS_KEY environment variable is required" .Values.env.MINIO_ACCESS_KEY | quote }}
        - name: MINIO_SECRET_KEY
          value: {{ required "MINIO_SECRET_KEY environment variable is required" .Values.env.MINIO_SECRET_KEY | quote }}
        - name: USE_AUTH
          value: {{ required "USE_AUTH environment variable is required" .Values.env.USE_AUTH | quote }}
        - name: KEYCLOAK_ID
          value: {{ required "KEYCLOAK_ID environment variable is required" .Values.env.KEYCLOAK_ID | quote }}
        - name: KEYCLOAK_SECRET
          value: {{ required "KEYCLOAK_SECRET environment variable is required" .Values.env.KEYCLOAK_SECRET | quote }}
        - name: TOKEN_ISSUER_URL
          value: {{ required "TOKEN_ISSUER_URL environment variable is required" .Values.env.TOKEN_ISSUER_URL | quote }}
        - name: POSTGRES_USER
          value: {{ required "POSTGRES_USER environment variable is required" .Values.env.POSTGRES_USER | quote }}
        - name: POSTGRES_DATABASE
          value: {{ required "POSTGRES_DATABASE environment variable is required" .Values.env.POSTGRES_DATABASE | quote }}
        - name: POSTGRES_PASSWORD
          value: {{ required "POSTGRES_PASSWORD environment variable is required" .Values.env.POSTGRES_PASSWORD | quote }}
        - name: PYTHONUNBUFFERED
          value: {{ required "PYTHONUNBUFFERED environment variable is required" .Values.env.PYTHONUNBUFFERED | quote }}
        - name: CELERYD_HIJACK_ROOT_LOGGER 
          value: {{ required "CELERYD_HIJACK_ROOT_LOGGER  environment variable is required" .Values.env.CELERYD_HIJACK_ROOT_LOGGER  | quote }}
        - name: CELERY_RESULT_BACKEND
          value: {{ required "CELERY_RESULT_BACKEND environment variable is required" .Values.env.CELERY_RESULT_BACKEND | quote }}
        - name: CELERY_BROKER_URL
          value: {{ required "CELERY_BROKER_URL environment variable is required" .Values.env.CELERY_BROKER_URL | quote }}

        ports:
        - containerPort: 8006