apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-{{ .Values.app.service.name }}"
  labels:
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 80
      protocol: TCP
      targetPort: 8081
  selector:
    app: {{ .Values.app.service.name }}
    release: {{ .Release.Name }}
