{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
spec:
  rules:
    - host: {{ .Values.backend.host }}
      http:
        paths:
          - backend:
              service:
                name: "{{ .Release.Name }}-deeptsf-backend"
                port:
                  number: 80
            path: / 
            pathType: Prefix 
    - host: {{ .Values.dagster.host }}
      http:
        paths:
          - backend: 
              service: 
                name: "{{ .Release.Name }}-deeptsf-dagster" 
                port: 
                  number: 80
            path: / 
            pathType: Prefix 

{{- end }}
