apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "deeptsf-backend.fullname" . }}
  labels:
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.service.name }}
      release: {{ .Release.Name }} 
  template:
    metadata:
      labels:
        app: {{ .Values.app.service.name }}
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets: 
      - name: {{ .Release.Name }}-image-pull-secret
      containers:
      - name: {{ include "deeptsf-backend.name" . | replace "_" "-" }}
        image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
        imagePullPolicy: Always
        resources:
          limits:
            memory: {{ .Values.app.memory_limit | quote }}
        env:
          - name: MINIO_SSL
            value: {{ .Values.minio.ssl | quote }}
        envFrom:
        - configMapRef:
            name: {{ include "deeptsf-backend.fullname" . }}-cm
        ports:
        - containerPort: 80