{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-deeptsf-ingress
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  labels:
    release: {{ .Release.Name }}

spec:
  tls:
    - hosts:
        - {{ .Values.backend.host }}
        - {{ .Values.dagster.host }}
      secretName: "{{ .Values.ingress.tlsSecretName }}"
  rules:
    - host: {{ .Values.backend.host }}
      http:
        paths:
          - backend:
              service:
                name: "{{ .Release.Name }}-deeptsf-backend"
                port:
                  number: 80
            path: / 
            pathType: Prefix 
    - host: {{ .Values.dagster.host }}
      http:
        paths:
          - backend: 
              service: 
                name: "{{ .Release.Name }}-deeptsf-dagster" 
                port: 
                  number: 80
            path: / 
            pathType: Prefix 

{{- end }}
