{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-deeptsf-backend-ingress
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  labels:
    release: {{ .Release.Name }}

spec:
  rules:
    - host: "deeptsf-backend{{ .Values.env.host }}"
      http:
        paths:
          - backend:
              service:
                name: "{{ .Release.Name }}-deeptsf-backend"
                port:
                  number: 80
            path: / 
            pathType: Prefix 
    - host: "deeptsf-dagster{{ .Values.env.host }}"
      http:
        paths:
          - backend: 
              service: 
                name: "{{ .Release.Name }}-deeptsf-dagster" 
                port: 
                  number: 80
            path: / 
            pathType: Prefix 
    # - host: "deeptsf-pgdb{{ .Values.env.host }}"
    #   http:
    #     paths:
    #       - backend: 
    #           service: 
    #             name: "{{ .Release.Name }}-deeptsf-pgdb" 
    #             port: 
    #               number: 80
    #         path: / 
    #         pathType: Prefix 
    # - host: "deeptsf-redis{{ .Values.env.host }}"
    #   http:
    #     paths:
    #       - backend: 
    #           service: 
    #             name: "{{ .Release.Name }}-deeptsf-redis" 
    #             port: 
    #               number: 80
    #         path: / 
    #         pathType: Prefix 
{{- end }}